# Generated by Django 4.1.7 on 2023-03-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cerviseclient_product_repairman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerviseclient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
