# Generated by Django 4.1.7 on 2023-03-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cerviseclient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerviseclient',
            name='client_reception_time',
            field=models.DateField(auto_now=True),
        ),
    ]
